### ISSUE TITLE
__FLAGGED_FW_NAME vs. Homie_setFirmware()

### ISSUE THREAD

**Issue by luebbe** [fablabnbg/ESP_HomieDoorControl#1]
Hi Ian,

out of curiosity: Why do you always include these two lines in your projects
```
const char *__FLAGGED_FW_NAME = "\xbf\x84\xe4\x13\x54" FW_NAME "\x93\x44\x6b\xa7\x75";
const char *__FLAGGED_FW_VERSION = "\x6a\x3f\x3e\x0e\xe1" FW_VERSION "\xb0\x30\x48\xd4\x1a";
```
Doesn't `Homie_setFirmware(FW_NAME, FW_VERSION)` handle everything correctly already?

**Comment by euphi** [comment]
Well, I think it was necessary for first OTA implementations and I just copypasta-ed it since then.. :thinking:
